### ISSUE TITLE
Improvement: Add Arrays and Complex Types on Simulation

### ISSUE THREAD

**Issue by pcbl** [Azure-Samples/iot-edge-opc-plc#12]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [X] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>

### Any log messages given by the failure
>

### Expected/desired behavior
>It would be nice if we have some Complex Types Generation on the Simulation. One that would create an array of Complex Types, another with a Single Instance just as a more "complex" kind of data that could be obtained from the OPC Server, something like:

- ArrayOfStringData : A simple array with Random String values
- ArrayOfFloatData : A simple array with Random Float values
- ArrayOfComplexData : An array from a given Complex Type(A class with at least 2 Attributes...)
- ComplexData : An instance of a Complex Type(A class with at least 2 Attributes...)

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by bzumik1** [comment]
I would also appreciate this.

**Comment by luiscantero** [comment]
What we support now are slow and fast nodes of type "UIntArray". And the option --ctb adds a simple boiler with a complex data type.

**Comment by algattik** [comment]
This is now supported with the --ref parameter (#51). @cristipogacean close?
