### ISSUE TITLE
V2.5.0 Broken

### ISSUE THREAD

**Issue by whakey** [Azure-Samples/iot-edge-opc-plc#175]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [x] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> Deploy to Azure using "Deploy to Azure" button. Can't connect using OPC UA Client. IIOT Opc UA Publisher module can't connect either.

### Expected/desired behavior
> Can connect using OPC UA client. Reverting to 2.4.2 works.

### Versions

> 2.5.0

### Mention any other details that might be useful
Log: [opcplclog.txt](https://github.com/Azure-Samples/iot-edge-opc-plc/files/9572932/opcplclog.txt)

Connection error from client: 
Please verify that the Server is available at the selected address.

Bad_ConnectionRejected (0x80AC0000) "Could not establish a network connection to remote server."

Failed to retrieve endpoints. The server is not available: opc.tcp://aci-contoso-aiui3mg-plc1.westeurope.azurecontainer.io:50000 
> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by gsgoodluck** [comment]
When  Plc Service Runing , how to use  MasterNodeManager  Multiple PLC

**Comment by luiscantero** [comment]
@whakey I just deployed using the button and I can connect as follows:
![image](https://user-images.githubusercontent.com/1353540/190686842-4d90fd3d-79a1-400f-9731-bf2e00006732.png)

**Comment by gsgoodluck** [comment]
<img width="587" alt="sss" src="https://user-images.githubusercontent.com/31750002/190746895-17ac1b23-1561-4233-a25d-fa19030e95b6.png">

**Comment by gsgoodluck** [comment]
When Connection Actual Device(Plc...),Check whether the device read/write request is here,
   Or how to handle actual device reads and writes

<img width="708" alt="rw" src="https://user-images.githubusercontent.com/31750002/190781246-e9d484f6-0962-41ce-a9d7-ab4162453542.png">

**Comment by luiscantero** [comment]
@gsgoodluck could you please open a new issue and explain in more detail what you need. This issue was opened by another user for another topic, thanks.

**Comment by whakey** [comment]
I tried again today, deployed completely fresh V2.5.0

Prosys OPC UA Browser, UA Expert and Azure IIOT Opc Publisher all fail to connect with BadTimeout errors, whereas all succeed with V2.4.2 (deployed using same template, just changed latest tag to 2.4.2)

Weird :D. If nobody else is having this issue then probably something is wrong on my end :(

**Comment by luiscantero** [comment]
Can you please confirm that your client uses security policy etc as in my screenshot above?

**Comment by luiscantero** [comment]
@whakey could you please try the new version 2.5.1

**Comment by whakey** [comment]
@luiscantero I just updated the tag from 2.4.2 to 2.5.1 and everything seems to be working!
