### ISSUE TITLE
Ability to import an XML NodeSet file into the simulator

### ISSUE THREAD

**Issue by GodlikePenguin** [Azure-Samples/iot-edge-opc-plc#215]
### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [X] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> N/A

### Any log messages given by the failure
> N/A

### Expected/desired behavior
> I would like to be able to provide one (or ideally multiple) [XML Nodeset files](https://github.com/OPCFoundation/UA-Nodeset) to the simulator, such that those Nodesets are included in the address space of the simulator. I am aware of nodefile.json, but as far as I can see this only supports putting nodes in a single folder which is a child of the root node, rather than replicating an existing address space.

### OS and Version?
> N/A

### Versions
> N/A

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by luiscantero** [comment]
@GodlikePenguin I'm looking into this. Loading the XML NodeSet file directly is difficult as the SDK currently does not provide an API to do it. But we can use the ModelCompiler to generate a PredefinedNodes.uanodes file and load it/them.
