### ISSUE TITLE
BuildInfo members not containing values

### ISSUE THREAD

**Issue by fabolo** [Azure-Samples/iot-edge-opc-plc#237]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [x ] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
trying to read ServerStatus->BuildInfo with a OPC-UA Foundation sample client I can read BuildInfo string but if I try to read the single members I get null values

I'm on Windows 10 Build 19044  source code compiled with VisualStudio 2022 Community 17.5.4

### Mention any other details that might be useful
I've tried the console reference server from OPC Foundation with the same client and it works fine

**Comment by luiscantero** [comment]
@fabolo this is what we see when we try:
![image](https://user-images.githubusercontent.com/1353540/235110782-435737d7-dca2-4be3-a4c8-70bc37561095.png)

Are you using the latest reference client and OPC-PLC server?

**Comment by luiscantero** [comment]
Apparently there was indeed an issue with BuildInfo that was fixed in the OPC UA SDK *.86. Please ensure that you are using OPC-PLC >= v2.8.4.

**Comment by fabolo** [comment]
downloaded 2.8.5 it works! With previous version, I was just starting to test my client, and I went: "what can I try to read? Let's try BuildInfo" :) Murphy's Law ruling the world...

**Comment by mregen** [comment]
see https://github.com/OPCFoundation/UA-.NETStandard/issues/2027
