### ISSUE TITLE
 publishednodes.json uses Standard NodeId not Expanded NodeId

### ISSUE THREAD

**Issue by RollsChris** [Azure-Samples/iot-edge-opc-plc#362]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ x] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>
Run the image and generate the publishednodes.json file

### Any log messages given by the failure
>

### Expected/desired behavior
>
Generated publishednodes.json uses standard NodeId not Expanded NodeId.

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by luiscantero** [comment]
@RollsChris the pn.json output uses expanded NodeId, e.g. `{ "Id": "nsu=http://microsoft.com/Opc/OpcPlc/Boiler;i=6211" }`

**Comment by RollsChris** [comment]
Yes but I would like away to use standard node IDs? Is that possible

**Comment by luiscantero** [comment]
Ok, from the title and description it sounded like right now we use standard nodeid and you would like to use expanded instead. Currently we don't support this. This file is generated for the Publisher, which understands this format. What is your use-case?

**Comment by luiscantero** [comment]
No response.
