### ISSUE TITLE
Variable nodes without type definition

### ISSUE THREAD

**Issue by LaurenceGA** [Azure-Samples/iot-edge-opc-plc#397]
### This issue is for a: (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce

Just running basic simulator then browsing with a client.

### Any log messages given by the failure

Screenshot of the node in question browsed via client.

<img width="1384" alt="image" src="https://github.com/user-attachments/assets/dc10cc9c-ed3d-425f-91b3-1722af7cbf34">

### Expected/desired behavior

These nodes have no references at all. Based on the spec [here](https://reference.opcfoundation.org/DI/v102/docs/4.2.1#:~:text=Object%20and%20Variable%20Nodes%20represent%20instances%20and%20they%20always%20reference%20a%20TypeDefinition) and [here](https://reference.opcfoundation.org/Core/Part3/v105/docs/4.6.1#:~:text=OPC%20UA%20Servers,information%20is%20available.), I would have expect nodes `ns=3;s=FastNumberOfUpdates` and `ns=3;s=SlowNumberOfUpdates` to have a `HasTypeDefinition` reference.

I'm not an expert, so maybe this is normal, or does this represent a non-compliant information model, or is it a bug?

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

macOS Sonoma 14.7

### Versions

Latest.

### Mention any other details that might be useful

Nodes seem to be created [here](https://github.com/Azure-Samples/iot-edge-opc-plc/blob/main/src/PluginNodes/SlowFastCommon.cs#L75-L92)

**Comment by LaurenceGA** [comment]
Thanks!

**Comment by luiscantero** [comment]
@LaurenceGA thanks for reporting it, have a nice weekend!
