### ISSUE TITLE
Support of OPC UA 1.04.365.48

### ISSUE THREAD

**Issue by eoursel** [Azure-Samples/iot-edge-opc-plc#44]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [X] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```
Do you plan to migrate to OPC UA 1.04.365  instead of OPC UA 1.04.363 ? To align with the new CertificateBuilder class and the others enhancements of version 1.04.365.

### Minimal steps to reproduce
>

### Any log messages given by the failure
> Compilation failed with 1.04.365.48 

### Expected/desired behavior
> Compiled with Nuget packages 1.04.365.48 (current version)

### OS and Version?
> NETCORE 3.1

### Versions
> Last version from trunK

**Comment by hansgschossmann** [comment]
We should definitely do this. Tagging as bug not as feature request.
