### ISSUE TITLE
Feature request: Support incoming commands

### ISSUE THREAD

**Issue by sandervandevelde** [Azure-Samples/iot-edge-opc-plc#7]
[X] feature request

Hello,

we want to test how the OPC-Twin supports sending commands to OPC-UA servers.

Is it possible to add handling commands to the OPC-PLC? Is this possible due to the usage of the standard OPC-UA server from the [UA-.NETStandard](https://github.com/OPCFoundation/UA-.NETStandard)?
We are happy to help. Can you point us in the right direction on how to add this feature?

Edit: With the OPCTwin, we see already a few methods available. So the question more like a guidance for adding your own methods next to the existing once. With or without parameters.

**Comment by hansgschossmann** [comment]
Sorry for the late response. What do you mean by "add handling commands"?
If it is about adding your own OPC methods, just use the existing as a blueprint.

**Comment by hansgschossmann** [comment]
If you still need to know how to run opc-twin standalone and use the direct method interface, pls let me know.

**Comment by hansgschossmann** [comment]
Just saw your comment on adding your own methods. OPCTwin has a framework, which wires up methods in a C# class as direct methods. You just need to add the rigth attributes to the class containing the methods.

**Comment by hansgschossmann** [comment]
@sandervandevelde pls check the implementation of the existing OPC UA methods "ResetStepUp", "StartStepUp" and "StopStepUp" which should show you how to add your own OPC UA methods.
Pls reactivate the issue, if this is not sufficient.
